### ISSUE TITLE
Choose of standard and clients

### ISSUE THREAD

**Issue by Spidfail** [Spidfail/irc_server#1]
Hello fellow collegues,

First of all, we need to define :
1. Which _client_ to choose as reference
2. Which _IP protocol_ we will use

These are my propositions :
1. **irssi** as client, because : it's a IRC reference, one of the most used client. It's also usable on terminal.
2. **IPV6** : because why not ? It's today standard. However the clients may need an IPV4 support.

**Comment by hamanmax** [comment]
i'm agree on both i have also look for irc client and i found irssi very good we can use it

**Comment by Spidfail** [comment]
Nice, @Drwuu have no problem with it eather (we discussed it later)

I can close it.
