### ISSUE TITLE
Messages max length

### ISSUE THREAD

**Issue by Spidfail** [Spidfail/irc_server#14]
## Situation
There is some limitations of size depending on what input the server expects.

I'll list all limits found rfc 1459 :
 - **User** nickname : 9 char
 - **Services** nickname : 9 char
 - **Channel** names : 50 char
 - **IRC Messages** : 512 char, 510 char ("_for the command and its parameters_")
 
 In "Message format" (rfc 1459 - 2.3) :
  - <**hostname**> : 63 char (within the _IRC Message_ limitation and because of it)
  
## Suggestions
The Proxy class will **limit** the buffer size to **512 char** for reason of safety/implementation.

I think we can manage the other length limitations server side because we need to parse raw data for such purpose.

Tell me if you are okay with it and how we can manage it.
Thanks !

**Comment by Drwuu** [comment]
I got it
