### ISSUE TITLE
Division of Labour

### ISSUE THREAD

**Issue by Spidfail** [Spidfail/irc_server#2]
Hi,
We need to be clear about division of labour, as it's different from other group projects. I don't see a simple division as the minishell's parsing/execution thing.

My idea is to divide tasks as we go along the project.
For example : 
 - One can explore socket communication
 - The other one the client parameters we need to manage
 - The last one the structure of IRC canal -> operators, canal creation, canal deletion...
 
 Told me what you think about it,
 I'm open to other's ideas (ofc.)

**Comment by Drwuu** [comment]
Let's meet on discord or IRL.
Max, are you available those times ? At school it could be better, but if you can't, we can discuss about it right now on discord.

**Comment by hamanmax** [comment]
yeah i'll come tomorrow all day long

**Comment by hamanmax** [comment]
i've start to create the structure of the code / classes with the right Protocole i'll push today
