### ISSUE TITLE
Commit and Branch naming

### ISSUE THREAD

**Issue by Spidfail** [Spidfail/irc_server#4]
Hi,
I was wondering, how do you want to identify your commits ?
Moreover, what structure could we adopt to store our work and test properly ?

## Commit

I propose a simple identification zone in front of all commits. That's what I'm using on my own repo'. The cool part is that you can retrieve what part this commit was member (connexion, structure, client...) and what you were dealing.

Example  :
- [[TEST - CONNECTION] First tests server - client](https://github.com/Spidfail/irc_server/commit/be8c120a5369671ec86e3a07817965575f68ba2d).   
The work saved in this commit will not be part of the main process, because it's all tests to implement connection later.

## Branch

I propose a best structure than using our own branch only with ou name. I created a new branch called [test/connection](https://github.com/Spidfail/irc_server/tree/test/connection) for that. I think it will give to the project a better view and a better way to organize it.

Feel free to give your opinion !

@Spidfail

**Comment by hamanmax** [comment]
we can often use branch when we want to work something and create a pull request after all in the pull request menu we can chose to delete a branch after it was merged like a did on the first one (i need to delete it)

**Comment by Spidfail** [comment]
Sounds good to me !
We need DrWuu's confirmation to close it (@Drwuu)
